// Generated by CoffeeScript 1.6.3
(function() {
  var auth, should;

  should = require("should");

  auth = require("../lib/main");

  describe("ember auth", function() {
    it("smoke", function() {
      var num;
      num = 2;
      return num.should.eql(2);
    });
    it("call on mod", function() {
      return auth.foo().should.eql(14);
    });
    return it("double", function() {
      return auth.double(4).should.eql(8);
    });
  });

}).call(this);
