// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = {};

  App.User = DS.Model.extend({
    email: DS.attr('string'),
    authentication_token: DS.attr('string'),
    providers: DS.attr("hash")
  });

  App.User.reopenClass({
    double: function(x) {
      return x * 2;
    }
  });

  App.User.FIXTURES = [
    {
      id: 1,
      email: "mharris717@gmail.com"
    }
  ];

  module.exports = App;

}).call(this);
