// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = {};

  App.Auth = Em.Auth.create({
    signInEndPoint: '/users/sign_in.json',
    signOutEndPoint: '/logout',
    userModel: 'App.User',
    tokenKey: "auth_token",
    tokenIdKey: "user_id",
    sessionAdapter: 'cookie',
    modules: ['emberData', 'rememberable'],
    rememberable: {
      tokenKey: 'auth_token',
      period: 14,
      autoRecall: true
    }
  });

  App.Auth.on("signInSuccess", function() {
    console.debug("signed in");
    return setTimeout(function() {
      var c, classes, _i, _len, _results;
      classes = App.$userRefreshClasses;
      if (classes) {
        _results = [];
        for (_i = 0, _len = classes.length; _i < _len; _i++) {
          c = classes[_i];
          _results.push(c.find());
        }
        return _results;
      }
    }, 1000);
  });

  module.exports = App;

}).call(this);
