// Generated by CoffeeScript 1.6.3
(function() {
  var auth;

  require("./module_setup");

  auth = {
    foo: function() {
      return 14;
    },
    double: function(x) {
      return x * 2;
    },
    controllers: require("./controllers/sign_in"),
    models: require("./models/user"),
    Auth: require("./auth_setup")
  };

  module.exports = auth;

}).call(this);
