// Generated by CoffeeScript 1.6.3
(function() {
  var auth;

  auth = {
    foo: function() {
      return 14;
    },
    double: function(x) {
      return x * 2;
    }
  };

  module.exports = auth;

}).call(this);
