// Generated by CoffeeScript 1.6.3
(function() {
  var auth, possAct;

  possAct = function(f) {
    if (typeof Em === 'undefined') {
      return f;
    } else {
      return f();
    }
  };

  auth = {
    foo: function() {
      return 14;
    },
    double: function(x) {
      return x * 2;
    },
    controllers: possAct(function() {
      return require("./controllers/sign_in");
    }),
    models: possAct(function() {
      return require("./models/user");
    }),
    Auth: possAct(function() {
      return require("./auth_setup");
    }),
    setup: require('./module_setup'),
    setupApp: function(app) {
      app.User = this.models.User;
      app.SignInController = this.controllers.SignInController;
      app.SignOutController = this.controllers.SignOutController;
      return app.Auth = this.Auth;
    }
  };

  module.exports = auth;

}).call(this);
