// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  App = {};

  App.SignInController = Em.ObjectController.extend({
    init: function() {
      this._super();
      return this.set("content", Em.Object.create());
    },
    login: function() {
      return App.Auth.signIn({
        data: {
          "email": this.$email,
          "password": this.$password
        }
      });
    },
    double: function(x) {
      return x * 2;
    }
  });

  App.SignOutController = Em.ObjectController.extend({
    init: function() {
      this._super();
      return this.set("content", Em.Object.create());
    },
    logout: function() {
      console.debug("logout");
      App.Auth.get("_session").clear();
      return App.Auth.trigger("signOutSuccess");
    }
  });

  module.exports = App;

}).call(this);
